const Koa = require('koa')
const app = new Koa()
const json = require('koa-json')
const bodyParser = require('koa-bodyparser')
const router = require('koa-router')()
const cors = require('koa2-cors')
const abnormal = require('./config/abnormal')

app.use(cors())
app.use(json())
app.use(bodyParser())
app.use(abnormal)


//注册登录
const login = require('./router/login')
const game = require('./router/game')
const game_search = require('./router/game_search')
const game_add = require('./router/game_add')
const game_locate = require('./router/game_locate')
const game_edit = require('./router/game_edit')
const game_delete = require('./router/game_delete')
const grade_search = require('./router/grade_search')
const grade_upload = require('./router/grade_upload')
const playergrade_search = require('./router/playergrade_search')
const user = require('./router/user')
const user_search = require('./router/user_search')
const user_locate = require('./router/user_locate')
const upload = require('./router/upload')
const user_edit = require('./router/user_edit')
const user_delete = require('./router/user_delete')
const comment_get = require('./router/comment_get')
const comment_del = require('./router/comment_del')
const comment_search = require('./router/comment_search')
const activity_get = require('./router/activity_get')
const activity_check = require('./router/activity_check')
const activity_delete = require('./router/activity_delete')
const activity_msg = require('./router/activity_msg')
const activity_search = require('./router/activity_search')

//配置路由接口
router.use('/api',login)
router.use('/api',game)
router.use('/api',game_search)
router.use('/api',game_add)
router.use('/api',game_locate)
router.use('/api',game_edit)
router.use('/api',game_delete)
router.use('/api',grade_search)
router.use('/api',grade_upload)
router.use('/api',playergrade_search)
router.use('/api',user)
router.use('/api',user_search)
router.use('/api',user_locate)
router.use('/api',upload)
router.use('/api',user_edit)
router.use('/api',user_delete)
router.use('/api',comment_get)
router.use('/api',comment_del)
router.use('/api',comment_search)
router.use('/api',activity_get)
router.use('/api',activity_check)
router.use('/api',activity_delete)
router.use('/api',activity_msg)
router.use('/api',activity_search)

//启动路由
app.use(router.routes()).use(router.allowedMethods())
//自定义端口，不能和其他程序冲突
app.listen(3000)
console.log('成功')